version: 2.0

jobs:
  test:
    docker:
      - image: circleci/node:8.11.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

  publish:
    docker:
      - image: circleci/node:8.11.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm run build-lib
      - run: cp ./CHANGELOG.md ./dist/smarti18n/CHANGELOG.md
      - run: cp ./LICENSE ./dist/smarti18n/LICENSE
      - run: npm publish ./dist/smarti18n

workflows:
  version: 2
  commits:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
  releases:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
